// eslint-disable-next-line @typescript-eslint/no-var-requires
const { jsExtensions } = require("./extensions");

module.exports = {
  parserOptions: {
    sourceType: "module",
    ecmaVersion: 2022,
    ecmaFeatures: {
      impliedStrict: true,
      jsx: true,
    },
  },
  env: {
    es2022: true,
    jest: true,
  },
  globals: {
    console: false,
    exports: false,
    global: false,
    module: false,
    require: false,
  },
  plugins: [
    "node",
  ],
  rules: {
    "@stylistic/array-bracket-spacing": ["warn", "never"],
    "@stylistic/arrow-spacing": ["warn", { before: true, after: true }],
    "@stylistic/block-spacing": ["warn", "always"],
    "@stylistic/comma-dangle": ["warn", "always-multiline"],
    "@stylistic/comma-spacing": ["warn", { before: false, after: true }],
    "@stylistic/comma-style": ["warn", "last"],
    "@stylistic/computed-property-spacing": ["warn", "never"],
    "@stylistic/dot-location": ["warn", "property"],
    "@stylistic/eol-last": "warn",
    "@stylistic/func-call-spacing": ["warn", "never"],
    "@stylistic/generator-star-spacing": ["warn", "after"],
    "@stylistic/indent": ["error", 2],
    "@stylistic/jsx-quotes": ["error", "prefer-double"],
    "@stylistic/new-parens": "warn",
    "@stylistic/no-extra-semi": "warn",
    "@stylistic/no-floating-decimal": "warn",
    "@stylistic/no-mixed-spaces-and-tabs": "warn",
    "@stylistic/no-trailing-spaces": "warn",
    // "@stylistic/no-unused-vars": "error",
    "@stylistic/no-whitespace-before-property": "warn",
    "@stylistic/operator-linebreak": ["warn", "after", { overrides: { "?": "before", ":": "before" } }],
    "@stylistic/quotes": ["error", "double"],
    "@stylistic/rest-spread-spacing": ["warn", "never"],
    "@stylistic/semi": "error",
    "@stylistic/semi-spacing": ["warn", { before: false, after: true }],
    "@stylistic/semi-style": ["warn", "last"],
    "@stylistic/space-before-blocks": ["warn", "always"],
    "@stylistic/space-before-function-paren": ["warn", { anonymous: "never", named: "never" }],
    "@stylistic/space-in-parens": ["warn", "always"],
    "@stylistic/space-infix-ops": "warn",
    "@stylistic/switch-colon-spacing": ["warn", { before: false, after: true }],
    "@stylistic/template-curly-spacing": ["warn", "never"],
    "@stylistic/template-tag-spacing": ["warn", "never"],
    "@stylistic/yield-star-spacing": ["warn", "after"],
    "constructor-super": "warn",
    "getter-return": "warn",
    "no-alert": "off",
    "no-array-constructor": "warn",
    "no-caller": "warn",
    "no-case-declarations": "warn",
    "no-compare-neg-zero": "warn",
    "no-cond-assign": "warn",
    "no-const-assign": "error",
    "no-constant-condition": ["warn", { checkLoops: false }],
    "no-control-regex": "off",
    "no-debugger": "warn",
    "no-delete-var": "error",
    "no-dupe-args": "error",
    "no-dupe-class-members": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty-character-class": "warn",
    "no-empty-pattern": "warn",
    "no-eval": "warn",
    "no-ex-assign": "warn",
    "no-extend-native": "warn",
    "no-extra-bind": "warn",
    "no-extra-boolean-cast": "warn",
    "no-fallthrough": "warn",
    "no-func-assign": "error",
    "no-global-assign": "warn",
    "no-implied-eval": "warn",
    "no-inner-declarations": "warn",
    "no-invalid-regexp": "error",
    "no-irregular-whitespace": "warn",
    "no-iterator": "warn",
    "no-label-var": "warn",
    "no-labels": ["warn", { allowLoop: true, allowSwitch: true }],
    "no-lone-blocks": "warn",
    "no-multi-assign": "warn",
    "no-new": "warn",
    "no-new-func": "warn",
    "no-new-object": "warn",
    "no-new-symbol": "error",
    "no-obj-calls": "warn",
    "no-octal": "warn",
    "no-octal-escape": "warn",
    "no-proto": "warn",
    "no-redeclare": "warn",
    "no-return-assign": "warn",
    "no-script-url": "warn",
    "no-self-assign": "warn",
    "no-self-compare": "warn",
    "no-sequences": "warn",
    "no-shadow-restricted-names": "warn",
    "no-sparse-arrays": "warn",
    "no-this-before-super": "warn",
    "no-throw-literal": "warn",
    "no-undef": "error",
    "no-unexpected-multiline": "warn",
    "no-unneeded-ternary": "warn",
    "no-unreachable": "warn",
    "no-unsafe-negation": "warn",
    "no-unused-expressions": ["warn", { allowShortCircuit: true, enforceForJSX: true }],
    "no-unused-labels": "warn",
    "no-unused-vars": "error",
    "no-useless-computed-key": "warn",
    "no-useless-concat": "warn",
    "no-useless-constructor": "warn",
    "no-useless-escape": "warn",
    "no-useless-rename": "warn",
    "no-useless-return": "warn",
    "no-var": "warn",
    "no-void": "warn",
    "no-with": "warn",
    "object-shorthand": "warn",
    "prefer-const": ["warn", { destructuring: "all", ignoreReadBeforeAssign: true }],
    "prefer-promise-reject-errors": "warn",
    "prefer-rest-params": "warn",
    "prefer-spread": "warn",
    "unicode-bom": ["warn", "never"],
    "use-isnan": "error",
    "valid-typeof": "error",
    "@stylistic/object-property-newline": ["error", { allowAllPropertiesOnSameLine: true }],
    curly: ["warn", "all"],
    eqeqeq: ["warn", "smart"],
    radix: "warn",
    yoda: ["warn", "never", { exceptRange: true }],
    "node/handle-callback-err": ["warn", "^(e|err|error|.+GlobalError)$"],
    "node/no-new-require": "warn",
  },
};
